# Generated by Django 4.1 on 2022-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="short_code",
            field=models.CharField(default="djgRozUDwv", max_length=50),
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="url",
        ),
        migrations.AddField(
            model_name="userdata",
            name="url",
            field=models.ManyToManyField(to="home.url"),
        ),
    ]
