# Generated by Django 4.1 on 2022-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_url_options_url_name_alter_url_short_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="url",
            options={},
        ),
        migrations.AddField(
            model_name="url",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
