# Generated by Django 4.1 on 2022-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_url_options_url_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
